spin_manifest_version = 2

[application]
authors = ["lounge fredlunden@gmail.com"]
description = ""
name = "frontend"
version = "0.1.6"


[[trigger.http]]
route = "/..."
component = "frontend"

[component.frontend]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.2/spin_static_fs.wasm", digest = "sha256:65456bf4e84cf81b62075e761b2b0afaffaef2d0aeda521b245150f76b96421b" }
files = [{ source = "dist", destination = "/" }]
environment = { FALLBACK_PATH = "index.html" }
sqlite_databases = ["default"]

[component.frontend.build]
command = "npm run build"
