spin_manifest_version = 2

[application]
name = "backend"
version = "0.1.0"
authors = ["lounge fredlunden@gmail.com"]
description = "lounge by lounge backend"

[[trigger.http]]
route = "/..."
component = "backend"

[component.backend]
source = "../target/app.wasm"
sqlite_databases = ["default"]

[component.backend.build]
command = "componentize-py -w spin-http componentize app -o ../target/app.wasm"
watch = ["*.py", "requirements.txt"]
